version: 3

tasks:
  default:
    cmds:
      - deno fmt .
      - gofmt -w .
      - golangci-lint run --fix --timeout "10m"
      - go test ./... -v
  build:
    cmds:
      - |
          rm -Rf .build/
          mkdir -p .build/
          cd .build
          go run ../agent/main.go \
            --message "Create a Node.js Express application with two endpoints: GET /hello that returns 'Hello World' and GET /time that returns the current time in JSON format. Include package.json with proper dependencies, a main server file, and any necessary setup."
